### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by cblgh**
adding lgpl 3.0, as in many of the other repos in the org. any thoughts? 

cc @arj03 @staltz @mycognosist @cryptix

### CODE REVIEW

**Review by staltz — APPROVED** [review]
:burrito:

**Comment by mycognosist** [comment]
🍣

**Comment by arj03** [comment]
Yeeeeeeeeeeeeeees :rocket:

**Comment by cryptix** [comment]
Not to party 💩 but AFAIK the sad reality is, a single LICENSE file is not enough.

All the files need to be marked individually. Common practice is SPDX headers these days

i.e.: https://github.com/cryptoscope/ssb/commit/a781ad4ee51523df1d3858d9859c285d0eeb2fb1#diff-224914deba718c5dabc4b6c82b1e807c9839e692c9571a0b9b72486165eb72b2R1

You can do this with `sed` pretty easily but I really recommend the [reuse tool](https://reuse.software/tutorial/)


1. `reuse lint`
2. check output file list for files missing info
3. `reuse addheader --copyright="The netsim authors" --license=$license $missingfiles`
4. `reuse download $license`
5. goto 1 until the list is empty

that's pretty much it :)

**Comment by cblgh** [comment]
@cryptix i downloaded & applied reuse per your instructions (thanks for them!)

mind giving a final review :heavy_check_mark:? :)

**Review by cryptix — COMMENTED** [review]
i think this looks good!

only nitpick: if you use "the xyz authors" I think you should have a AUTHORS file that lists them out.

**Pull request merged**
